// Define constants
const gravitationalAcceleration = 9.81; // m*s^-2
const gravitationalConstant = 6.67430e-11; // N*m^2*kg^-2
const constantOfAvogadro = 6.02214129e23; // mol^-1
const constantOfBoltzmann = 1.3806488e-23; // J*K^-1
const constantOfStefanBoltzmann = 5.670373e-8; // W*m^-2*K^-4
const constantOfWien = 2.8977721e-3; // m*K
const constantOfPlanck = 6.62606957e-34; // J*s
const constantOfFaraday = 9.64853365e4; // C*mol^-1
const speedOfLight = 2.99792458e8; // m*s^-1
const electricalPermittivityOfTheVacuum = 8.854187817e-12; // F*m^-1
const magneticPermeabilityOfTheVacuum = 1.25664e-6; // H*m^-1
const elementaryChargeQuantum = 1.602176565e-19; // C
const standardPressure = 1.01325e5; // Pa
const molarVolume273K = 2.2413968e-2; // m^3*mol^-1 | this contant only holds for gases under standard pressure.
const molarVolume298K = 2.45e-2; // m^3*mol^-1 | this constant only holds for gases under standard pressure.
const protonMass = 1.672621777e-27; // kg
const neutronMass = 1.674927351e-27; // kg
const electronMass = 9.10938291e-31; // kg
const planckLength = 1.616252e-35; // m
const planckMass = 2.17644e-8; // kg
const planckTime = 5.39124e-44; // s
const planckTemperature = 1.416785e32; // K
const magneticFluxquantum = 2.067833667e-15; // Wb
const constantOfVonKlitzing = 2.5812807557e4; // Ω
const conductivityQuantum = 7.7480917004e-5; // S
const universalGasConstant = 8.3144621; // J*mol^-1*K^-1

// Export constants
module.exports.gravitationalAcceleration = gravitationalAcceleration;
module.exports.gravitationalConstant = gravitationalConstant;
module.exports.constantOfAvogadro = constantOfAvogadro;
module.exports.constantOfBoltzmann = constantOfBoltzmann;
module.exports.constantOfStefanBoltzmann = constantOfStefanBoltzmann;
module.exports.constantOfWien = constantOfWien;
module.exports.constantOfPlanck = constantOfPlanck;
module.exports.constantOfFaraday = constantOfFaraday;
module.exports.speedOfLight = speedOfLight;
module.exports.electricalPermittivityOfTheVacuum = electricalPermittivityOfTheVacuum;
module.exports.magneticPermeabilityOfTheVacuum = magneticPermeabilityOfTheVacuum;
module.exports.elementaryChargeQuantum = elementaryChargeQuantum;
module.exports.standardPressure = standardPressure;
module.exports.molarVolume273K = molarVolume273K;
module.exports.molarVolume298K = molarVolume298K;
module.exports.protonMass = protonMass;
module.exports.neutronMass = neutronMass;
module.exports.electronMass = electronMass;
module.exports.planckLength = planckLength;
module.exports.planckMass = planckMass;
module.exports.planckTime = planckTime;
module.exports.planckTemperature = planckTemperature;
module.exports.magneticFluxquantum = magneticFluxquantum;
module.exports.constantOfVonKlitzing = constantOfVonKlitzing;
module.exports.conductivityQuantum = conductivityQuantum;
module.exports.universalGasConstant = universalGasConstant;
